// <auto-generated />
namespace KetClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _20153 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20153));
        
        string IMigrationMetadata.Id
        {
            get { return "201501121346239_2015-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
