// <auto-generated />
namespace KetClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _20155 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20155));
        
        string IMigrationMetadata.Id
        {
            get { return "201501131416253_2015-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
